### ISSUE TITLE
Solution to sendtokindle personal documents

### ISSUE THREAD

**Issue by erens-basement** [arpanghosh8453/kindle-stats#1]
Hi I saw your reddit post as I was looking for better analytics for my Kindle reading. However for the past year, I've been sideloading all my books via Sendtokindle, and like you've stated, all metadata gets stripped during the conversion and makes it very difficult to determine with the tags.

Is there any way for this script to work if I don't have a list of my books and relevant metadata? I'm fine with just the meaningless tags as books, luckily I've tracked my books on the side with GoodReads, so I should be able to manually determine them.

**Comment by arpanghosh8453** [comment]
Hey there, thanks for reaching out! 

I think the issue is the script is very easy and short, so you can alter it to your needs. I have just used the additional Calibre database to identify the books with names from the ASIN given. Do you know a little bit of python? Are you stuck at any specific point?

**Comment by erens-basement** [comment]
I'm not familiar with python or jupyter notebooks, but I'll see what I can do.
